"""Spinal Central Pattern Generator (CPG) for bipedal locomotion.

Uses the Matsuoka oscillator formulation — the standard rate-based
half-center model used in virtually all successful CPG-based robots.

Architecture:
  4 Matsuoka units: left_flex, left_ext, right_flex, right_ext
  Within-leg: mutual inhibition (flex ↔ ext)
  Between-legs: crossed inhibition (left ↔ right)
  Self-adaptation: each unit fatigues after sustained activity

The brain provides tonic drive that modulates speed.
Proprioceptive feedback entrains the oscillation to the body.

References:
    Matsuoka (1985). Sustained oscillations generated by mutually
    inhibiting neurons with adaptation.
    Ijspeert (2008). Central pattern generators for locomotion control.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np


@dataclass
class CPGParams:
    """Parameters for the Matsuoka CPG."""

    tau: float = 50.0           # Activity time constant (ms)
    tau_adapt: float = 300.0    # Adaptation time constant (ms) — must be > tau
    drive: float = 1.0          # Default tonic drive
    w_mutual: float = 2.5       # Mutual inhibition within leg (flex ↔ ext)
    w_crossed: float = 1.5      # Crossed inhibition between legs
    beta: float = 2.0           # Adaptation strength
    w_hip_knee: float = 0.7     # Hip-knee coupling (1.0 = locked, 0 = independent)
    proprio_gain: float = 0.5   # Proprioceptive feedback strength


class MatsuokaUnit:
    """Single Matsuoka oscillator unit (half of a half-center pair)."""

    def __init__(self, init_x: float = 0.0):
        self.x = init_x       # Activity variable
        self.a = 0.0           # Adaptation variable
        self.y = max(0, init_x)  # Output (rectified activity)

    def step(self, dt: float, drive: float, inhibition: float,
             tau: float, tau_a: float, beta: float) -> float:
        """Update one timestep. Returns output y."""
        dx = (-self.x + drive + inhibition - beta * self.a) / tau
        da = (-self.a + self.y) / tau_a

        self.x += dt * dx
        self.a += dt * da
        self.y = max(0, self.x)

        return self.y


class SpinalCPG:
    """Bipedal spinal CPG with Matsuoka oscillator architecture.

    Produces alternating flexor/extensor activity for left and right legs.
    The oscillation frequency is determined by tau and tau_adapt.
    The amplitude is determined by the tonic drive.
    """

    def __init__(self, params: CPGParams | None = None):
        self.p = params or CPGParams()

        # 4 units: break symmetry with different initial conditions
        self.left_flex = MatsuokaUnit(init_x=0.5)
        self.left_ext = MatsuokaUnit(init_x=-0.3)
        self.right_flex = MatsuokaUnit(init_x=-0.3)
        self.right_ext = MatsuokaUnit(init_x=0.5)

    def step(
        self,
        dt: float,
        brain_drive: float = 0.0,
        proprio_left: float = 0.0,
        proprio_right: float = 0.0,
    ) -> np.ndarray:
        """One CPG timestep.

        Args:
            dt: Timestep in ms.
            brain_drive: Modulation from brain [-1, 2].
                        0 = default rhythm, positive = faster/stronger.
            proprio_left: Left leg proprioceptive signal [-1, 1].
                         Positive = leg extended → promotes flexion.
            proprio_right: Same for right leg.

        Returns:
            [4] torques: [right_hip, right_knee, left_hip, left_knee]
            Range approximately [-1, 1].
        """
        p = self.p
        drive = p.drive + brain_drive

        # Read current outputs
        lf_y = self.left_flex.y
        le_y = self.left_ext.y
        rf_y = self.right_flex.y
        re_y = self.right_ext.y

        # Compute inhibition for each unit
        # Within-leg mutual inhibition
        lf_inhib = -p.w_mutual * le_y - p.w_crossed * rf_y
        le_inhib = -p.w_mutual * lf_y - p.w_crossed * re_y
        rf_inhib = -p.w_mutual * re_y - p.w_crossed * lf_y
        re_inhib = -p.w_mutual * rf_y - p.w_crossed * le_y

        # Proprioceptive modulation
        lf_drive = drive + p.proprio_gain * proprio_left
        le_drive = drive - p.proprio_gain * proprio_left
        rf_drive = drive + p.proprio_gain * proprio_right
        re_drive = drive - p.proprio_gain * proprio_right

        # Step all units
        self.left_flex.step(dt, lf_drive, lf_inhib, p.tau, p.tau_adapt, p.beta)
        self.left_ext.step(dt, le_drive, le_inhib, p.tau, p.tau_adapt, p.beta)
        self.right_flex.step(dt, rf_drive, rf_inhib, p.tau, p.tau_adapt, p.beta)
        self.right_ext.step(dt, re_drive, re_inhib, p.tau, p.tau_adapt, p.beta)

        # Convert to joint torques
        # Extension - Flexion gives net torque per leg
        left_torque = self.left_ext.y - self.left_flex.y
        right_torque = self.right_ext.y - self.right_flex.y

        # Scale to [-1, 1]
        scale = 2.0
        torques = np.array([
            np.clip(right_torque * scale, -1, 1),              # right hip
            np.clip(right_torque * scale * p.w_hip_knee, -1, 1),  # right knee
            np.clip(left_torque * scale, -1, 1),               # left hip
            np.clip(left_torque * scale * p.w_hip_knee, -1, 1),  # left knee
        ])

        return torques

    def get_state(self) -> dict:
        """Current CPG state for monitoring."""
        return {
            "left_flex": self.left_flex.y,
            "left_ext": self.left_ext.y,
            "right_flex": self.right_flex.y,
            "right_ext": self.right_ext.y,
            "left_torque": self.left_ext.y - self.left_flex.y,
            "right_torque": self.right_ext.y - self.right_flex.y,
        }

    def reset(self):
        """Reset CPG."""
        self.__init__(params=self.p)
